export enum ActionTypes {
    CLEAR_ALL_INGREDIENTS = "CLEAR_ALL_INGREDIENTS",
    GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST",
    GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS",
    GET_ORDER_DETAILS_FAILED = "GET_ORDER_DETAILS_FAILED",
}
