export enum ActionTypes {
    GET_ORDER_DETAILS_REQUEST = "GET_ORDER_DETAILS_REQUEST",
    GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS",
    GET_ORDER_DETAILS_FAILED = "GET_ORDER_DETAILS_FAILED",
}
