export enum ActionTypes {
    LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILED = "LOGIN_USER_FAILED",
    REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST",
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILED = "REGISTER_USER_FAILED",
}
