export enum ActionTypes {
    FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED",
    LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILED = "LOGIN_USER_FAILED",
    REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST",
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILED = "REGISTER_USER_FAILED",
    RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED",
}
