export enum ActionTypes {
    GET_BURGER_INGREDIENTS_REQUEST = "GET_BURGER_INGREDIENTS_REQUEST",
    GET_BURGER_INGREDIENTS_SUCCESS = "GET_BURGER_INGREDIENTS_SUCCESS",
    GET_BURGER_INGREDIENTS_FAILED = "GET_BURGER_INGREDIENTS_FAILED",
}
