export enum ActionTypes {
    WS_ORDERS_HISTORY_CONNECTION_START = "WS_ORDERS_HISTORY_CONNECTION_START",
    WS_ORDERS_HISTORY_CONNECTION_STOP = "WS_ORDERS_HISTORY_CONNECTION_STOP",
    WS_ORDERS_HISTORY_CONNECTION_SUCCESS = "WS_ORDERS_HISTORY_CONNECTION_SUCCESS",
    WS_ORDERS_HISTORY_CONNECTION_ERROR = "WS_ORDERS_HISTORY_CONNECTION_ERROR",
    WS_ORDERS_HISTORY_CONNECTION_CLOSED = "WS_ORDERS_HISTORY_CONNECTION_CLOSED",
    WS_GET_ORDERS_HISTORY = "WS_GET_ORDERS_HISTORY",
}
