export enum ActionTypes {
    ADD_INGREDIENT = "ADD_INGREDIENT",
    CLEAR_ALL_INGREDIENTS = "CLEAR_ALL_INGREDIENTS",
    DELETE_INGREDIENT = "DELETE_INGREDIENT",
    MOVE_INGREDIENTS = "MOVE_INGREDIENTS",
}
