export enum ActionTypes {
    WS_FEED_CONNECTION_START = "WS_FEED_CONNECTION_START",
    WS_FEED_CONNECTION_STOP = "WS_FEED_CONNECTION_STOP",
    WS_FEED_CONNECTION_SUCCESS = "WS_FEED_CONNECTION_SUCCESS",
    WS_FEED_CONNECTION_ERROR = "WS_FEED_CONNECTION_ERROR",
    WS_FEED_CONNECTION_CLOSED = "WS_FEED_CONNECTION_CLOSED",
    WS_GET_FEED = "WS_GET_FEED",
}
